// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2BKCU2PFEE9Xr2E-sVDSCNi12jddC0i4',
    appId: '1:333522677819:web:cf4e4fcc5f9ba90552ec1e',
    messagingSenderId: '333522677819',
    projectId: 'pomodoro-7fd38',
    authDomain: 'pomodoro-7fd38.firebaseapp.com',
    storageBucket: 'pomodoro-7fd38.appspot.com',
    measurementId: 'G-YM1TW6SMXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT89yzwiw4Pvds3uihj63xnpgaQ1nj2i4',
    appId: '1:333522677819:android:2bb30ef0e614e83152ec1e',
    messagingSenderId: '333522677819',
    projectId: 'pomodoro-7fd38',
    storageBucket: 'pomodoro-7fd38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMMTAymdQbnhyeZbFW_fctKiY0jkX2eP0',
    appId: '1:333522677819:ios:555c86a37d522ca952ec1e',
    messagingSenderId: '333522677819',
    projectId: 'pomodoro-7fd38',
    storageBucket: 'pomodoro-7fd38.appspot.com',
    iosClientId: '333522677819-bvp54tf5ssbvcbmm91omuvjr8p2jvmaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.pomodoro',
  );
}
